version: '3.3'
services:
  web:
    image: maxiplux/b2bcart-backend
    container_name: b2bcart-backend
    restart: on-failure
    environment:
      MONGO: mongo
      REDIS: redis
      DB: postgres
    ports:
      - "8080:8080"
    links:
      - postgres
      - mongo
      - redis
    depends_on:
      - postgres
      - mongo
      - redis


  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.7
    restart: on-failure
    ports:
      - '6379:6379'
  #  b2bcart-sonar:
  #    image: sonarqube:7.9.1-community
  #    ports:
  #      - 9001:9000
  #      - 9092:9092
  mongo:
    image: mongo:3.4.1
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
volumes:
  dbdata:
# this compomse no has it https://thepracticaldeveloper.com/2017/12/11/dockerize-spring-boot/ , but  that exmaple is beautiful because implements scale
