POST http://localhost:8080/oauth/token
Authorization: Basic YW5ndWxhcmFwcDoxMjM0NQ==
Postman-Token: 545bfb84-a4ff-4f96-ae85-89ee54fe0ec4
cache-control: no-cache
Content-Type: application/x-www-form-urlencoded

username=andres&password=12345&grant_type=password
<> 2019-08-23T103639.200.json
<> 2019-08-23T103621.200.json

###

